#!/usr/bin/env bun
import fs from 'fs'
import path from 'path'
import url from 'url'

const __dirname = path.dirname(url.fileURLToPath(import.meta.url))
const pkgPath = path.resolve(__dirname, '..', 'package.json')
const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf8')) as { version?: string }
const version = pkg.version ?? 'unknown'

const out = `// This file is generated by scripts/generate-version.ts\nexport const VERSION = "${version}"\n`
const outPath = path.resolve(__dirname, '..', 'src', 'version.ts')
fs.writeFileSync(outPath, out, 'utf8')
console.log('Generated', outPath)
